package edu.unapec.nomina.modelos;
// Generated Jun 8, 2017 1:25:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nombre;
     private String ubicacion;
     private boolean estado;
     private Set empleadodepartamentos = new HashSet(0);
     private Set empleadoses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(String nombre, String ubicacion, boolean estado) {
        this.nombre = nombre;
        this.ubicacion = ubicacion;
        this.estado = estado;
    }
    public Departamentos(String nombre, String ubicacion, boolean estado, Set empleadodepartamentos, Set empleadoses) {
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.empleadodepartamentos = empleadodepartamentos;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getEmpleadodepartamentos() {
        return this.empleadodepartamentos;
    }
    
    public void setEmpleadodepartamentos(Set empleadodepartamentos) {
        this.empleadodepartamentos = empleadodepartamentos;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


