package edu.unapec.nomina.modelos;
// Generated Jun 19, 2017 10:30:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nombre;
     private String ubicacion;
     private boolean estado;
     private Set empleadoses = new HashSet(0);
     private Set empleadoDepartamentos = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(String nombre, String ubicacion, boolean estado) {
        this.nombre = nombre;
        this.ubicacion = ubicacion;
        this.estado = estado;
    }
    public Departamentos(String nombre, String ubicacion, boolean estado, Set empleadoses, Set empleadoDepartamentos) {
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.empleadoses = empleadoses;
       this.empleadoDepartamentos = empleadoDepartamentos;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }
    public Set getEmpleadoDepartamentos() {
        return this.empleadoDepartamentos;
    }
    
    public void setEmpleadoDepartamentos(Set empleadoDepartamentos) {
        this.empleadoDepartamentos = empleadoDepartamentos;
    }




}


