package edu.unapec.nomina.modelos;
// Generated Jun 16, 2017 4:18:05 PM by Hibernate Tools 4.3.1



/**
 * EmpleadoDepartamentoId generated by hbm2java
 */
public class EmpleadoDepartamentoId  implements java.io.Serializable {


     private int idEmpleado;
     private int idDepartamento;

    public EmpleadoDepartamentoId() {
    }

    public EmpleadoDepartamentoId(int idEmpleado, int idDepartamento) {
       this.idEmpleado = idEmpleado;
       this.idDepartamento = idDepartamento;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoDepartamentoId) ) return false;
		 EmpleadoDepartamentoId castOther = ( EmpleadoDepartamentoId ) other; 
         
		 return (this.getIdEmpleado()==castOther.getIdEmpleado())
 && (this.getIdDepartamento()==castOther.getIdDepartamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpleado();
         result = 37 * result + this.getIdDepartamento();
         return result;
   }   


}


