package edu.unapec.nomina.modelos;
// Generated Jun 19, 2017 10:30:59 AM by Hibernate Tools 4.3.1



/**
 * EmpleadoDepartamento generated by hbm2java
 */
public class EmpleadoDepartamento  implements java.io.Serializable {


     private EmpleadoDepartamentoId id;
     private Departamentos departamentos;
     private Empleados empleados;

    public EmpleadoDepartamento() {
    }

    public EmpleadoDepartamento(EmpleadoDepartamentoId id, Departamentos departamentos, Empleados empleados) {
       this.id = id;
       this.departamentos = departamentos;
       this.empleados = empleados;
    }
   
    public EmpleadoDepartamentoId getId() {
        return this.id;
    }
    
    public void setId(EmpleadoDepartamentoId id) {
        this.id = id;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }




}


