package edu.unapec.nomina.modelos;
// Generated Jun 8, 2017 1:25:32 PM by Hibernate Tools 4.3.1



/**
 * Empleadodepartamento generated by hbm2java
 */
public class Empleadodepartamento  implements java.io.Serializable {


     private EmpleadodepartamentoId id;
     private Departamentos departamentos;
     private Empleados empleados;

    public Empleadodepartamento() {
    }

    public Empleadodepartamento(EmpleadodepartamentoId id, Departamentos departamentos, Empleados empleados) {
       this.id = id;
       this.departamentos = departamentos;
       this.empleados = empleados;
    }
   
    public EmpleadodepartamentoId getId() {
        return this.id;
    }
    
    public void setId(EmpleadodepartamentoId id) {
        this.id = id;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }




}


