package edu.unapec.nomina.modelos;
// Generated Jun 16, 2017 4:18:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private Departamentos departamentos;
     private Nominas nominas;
     private Puestos puestos;
     private String cedula;
     private String nombre;
     private BigDecimal salario;
     private boolean estado;
     private Set transaccioneses = new HashSet(0);
     private Set empleadoDepartamentos = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(Departamentos departamentos, Nominas nominas, Puestos puestos, String nombre, BigDecimal salario, boolean estado) {
        this.departamentos = departamentos;
        this.nominas = nominas;
        this.puestos = puestos;
        this.nombre = nombre;
        this.salario = salario;
        this.estado = estado;
    }
    public Empleados(Departamentos departamentos, Nominas nominas, Puestos puestos, String cedula, String nombre, BigDecimal salario, boolean estado, Set transaccioneses, Set empleadoDepartamentos) {
       this.departamentos = departamentos;
       this.nominas = nominas;
       this.puestos = puestos;
       this.cedula = cedula;
       this.nombre = nombre;
       this.salario = salario;
       this.estado = estado;
       this.transaccioneses = transaccioneses;
       this.empleadoDepartamentos = empleadoDepartamentos;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Nominas getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Nominas nominas) {
        this.nominas = nominas;
    }
    public Puestos getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Puestos puestos) {
        this.puestos = puestos;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set transaccioneses) {
        this.transaccioneses = transaccioneses;
    }
    public Set getEmpleadoDepartamentos() {
        return this.empleadoDepartamentos;
    }
    
    public void setEmpleadoDepartamentos(Set empleadoDepartamentos) {
        this.empleadoDepartamentos = empleadoDepartamentos;
    }




}


