package edu.unapec.nomina.modelos;
// Generated Jun 8, 2017 1:25:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private Departamentos departamentos;
     private Puestos puestos;
     private String cedula;
     private String nombre;
     private BigDecimal salario;
     private String idNomina;
     private boolean estado;
     private Set transaccioneses = new HashSet(0);
     private Set empleadodepartamentos = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(Departamentos departamentos, Puestos puestos, String nombre, BigDecimal salario, String idNomina, boolean estado) {
        this.departamentos = departamentos;
        this.puestos = puestos;
        this.nombre = nombre;
        this.salario = salario;
        this.idNomina = idNomina;
        this.estado = estado;
    }
    public Empleados(Departamentos departamentos, Puestos puestos, String cedula, String nombre, BigDecimal salario, String idNomina, boolean estado, Set transaccioneses, Set empleadodepartamentos) {
       this.departamentos = departamentos;
       this.puestos = puestos;
       this.cedula = cedula;
       this.nombre = nombre;
       this.salario = salario;
       this.idNomina = idNomina;
       this.estado = estado;
       this.transaccioneses = transaccioneses;
       this.empleadodepartamentos = empleadodepartamentos;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Puestos getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Puestos puestos) {
        this.puestos = puestos;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public String getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(String idNomina) {
        this.idNomina = idNomina;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set transaccioneses) {
        this.transaccioneses = transaccioneses;
    }
    public Set getEmpleadodepartamentos() {
        return this.empleadodepartamentos;
    }
    
    public void setEmpleadodepartamentos(Set empleadodepartamentos) {
        this.empleadodepartamentos = empleadodepartamentos;
    }




}


