package edu.unapec.nomina.modelos;
// Generated Jun 16, 2017 4:18:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nominas generated by hbm2java
 */
public class Nominas  implements java.io.Serializable {


     private Integer idNomina;
     private String descripcion;
     private Boolean estado;
     private Set empleadoses = new HashSet(0);

    public Nominas() {
    }

	
    public Nominas(String descripcion) {
        this.descripcion = descripcion;
    }
    public Nominas(String descripcion, Boolean estado, Set empleadoses) {
       this.descripcion = descripcion;
       this.estado = estado;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(Integer idNomina) {
        this.idNomina = idNomina;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


