package edu.unapec.nomina.modelos;
// Generated Jun 16, 2017 4:18:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Puestos generated by hbm2java
 */
public class Puestos  implements java.io.Serializable {


     private Integer idPuesto;
     private String descripcion;
     private String riesgo;
     private BigDecimal salarioMin;
     private BigDecimal salarioMax;
     private boolean estado;
     private Set empleadoses = new HashSet(0);

    public Puestos() {
    }

	
    public Puestos(String descripcion, String riesgo, BigDecimal salarioMin, BigDecimal salarioMax, boolean estado) {
        this.descripcion = descripcion;
        this.riesgo = riesgo;
        this.salarioMin = salarioMin;
        this.salarioMax = salarioMax;
        this.estado = estado;
    }
    public Puestos(String descripcion, String riesgo, BigDecimal salarioMin, BigDecimal salarioMax, boolean estado, Set empleadoses) {
       this.descripcion = descripcion;
       this.riesgo = riesgo;
       this.salarioMin = salarioMin;
       this.salarioMax = salarioMax;
       this.estado = estado;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(String riesgo) {
        this.riesgo = riesgo;
    }
    public BigDecimal getSalarioMin() {
        return this.salarioMin;
    }
    
    public void setSalarioMin(BigDecimal salarioMin) {
        this.salarioMin = salarioMin;
    }
    public BigDecimal getSalarioMax() {
        return this.salarioMax;
    }
    
    public void setSalarioMax(BigDecimal salarioMax) {
        this.salarioMax = salarioMax;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


