package edu.unapec.nomina.modelos;
// Generated Jun 16, 2017 4:18:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoIngresoDeduccion generated by hbm2java
 */
public class TipoIngresoDeduccion  implements java.io.Serializable {


     private Integer idTipoIngresoDeduccion;
     private String descripcion;
     private Boolean dependeSalario;
     private char tipo;
     private boolean estado;
     private Set transaccioneses = new HashSet(0);

    public TipoIngresoDeduccion() {
    }

	
    public TipoIngresoDeduccion(String descripcion, char tipo, boolean estado) {
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.estado = estado;
    }
    public TipoIngresoDeduccion(String descripcion, Boolean dependeSalario, char tipo, boolean estado, Set transaccioneses) {
       this.descripcion = descripcion;
       this.dependeSalario = dependeSalario;
       this.tipo = tipo;
       this.estado = estado;
       this.transaccioneses = transaccioneses;
    }
   
    public Integer getIdTipoIngresoDeduccion() {
        return this.idTipoIngresoDeduccion;
    }
    
    public void setIdTipoIngresoDeduccion(Integer idTipoIngresoDeduccion) {
        this.idTipoIngresoDeduccion = idTipoIngresoDeduccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getDependeSalario() {
        return this.dependeSalario;
    }
    
    public void setDependeSalario(Boolean dependeSalario) {
        this.dependeSalario = dependeSalario;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set transaccioneses) {
        this.transaccioneses = transaccioneses;
    }




}


