package edu.unapec.nomina.modelos;
// Generated Jun 8, 2017 1:25:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transacciones generated by hbm2java
 */
public class Transacciones  implements java.io.Serializable {


     private Integer idTransaccion;
     private Empleados empleados;
     private Tipoingresodeduccion tipoingresodeduccion;
     private String tipoTransaccion;
     private Date fecha;

    public Transacciones() {
    }

	
    public Transacciones(Empleados empleados, Tipoingresodeduccion tipoingresodeduccion, Date fecha) {
        this.empleados = empleados;
        this.tipoingresodeduccion = tipoingresodeduccion;
        this.fecha = fecha;
    }
    public Transacciones(Empleados empleados, Tipoingresodeduccion tipoingresodeduccion, String tipoTransaccion, Date fecha) {
       this.empleados = empleados;
       this.tipoingresodeduccion = tipoingresodeduccion;
       this.tipoTransaccion = tipoTransaccion;
       this.fecha = fecha;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Tipoingresodeduccion getTipoingresodeduccion() {
        return this.tipoingresodeduccion;
    }
    
    public void setTipoingresodeduccion(Tipoingresodeduccion tipoingresodeduccion) {
        this.tipoingresodeduccion = tipoingresodeduccion;
    }
    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


