package edu.unapec.nomina.modelos;
// Generated Jun 19, 2017 10:30:59 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transacciones generated by hbm2java
 */
public class Transacciones  implements java.io.Serializable {


     private Integer idTransaccion;
     private Empleados empleados;
     private TipoIngresoDeduccion tipoIngresoDeduccion;
     private String tipoTransaccion;
     private Date fecha;
     private BigDecimal monto;
     private boolean estado;

    public Transacciones() {
    }

	
    public Transacciones(Empleados empleados, TipoIngresoDeduccion tipoIngresoDeduccion, Date fecha, BigDecimal monto, boolean estado) {
        this.empleados = empleados;
        this.tipoIngresoDeduccion = tipoIngresoDeduccion;
        this.fecha = fecha;
        this.monto = monto;
        this.estado = estado;
    }
    public Transacciones(Empleados empleados, TipoIngresoDeduccion tipoIngresoDeduccion, String tipoTransaccion, Date fecha, BigDecimal monto, boolean estado) {
       this.empleados = empleados;
       this.tipoIngresoDeduccion = tipoIngresoDeduccion;
       this.tipoTransaccion = tipoTransaccion;
       this.fecha = fecha;
       this.monto = monto;
       this.estado = estado;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public TipoIngresoDeduccion getTipoIngresoDeduccion() {
        return this.tipoIngresoDeduccion;
    }
    
    public void setTipoIngresoDeduccion(TipoIngresoDeduccion tipoIngresoDeduccion) {
        this.tipoIngresoDeduccion = tipoIngresoDeduccion;
    }
    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


