package edu.unapec.nomina.modelos;
// Generated Aug 3, 2017 10:53:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String password;
     private boolean activo;
     private Set roleses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String password, boolean activo) {
        this.password = password;
        this.activo = activo;
    }
    public Usuario(String nombre, String password, boolean activo, Set roleses) {
       this.nombre = nombre;
       this.password = password;
       this.activo = activo;
       this.roleses = roleses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


